### ISSUE TITLE
"ValueError: arrays must all be the same length"

### ISSUE THREAD

**Issue by barnabemonnot** [csunlab/GISF2E#3]
Hello,
I am trying to run the program with a shapefile containing road information. The execution fails at this line:
`testando = pd.concat([testando,pd.DataFrame.from_dict(dicti)])`
It seems the fields of `dicti` have different lengths and so cannot be concatenated, e.g `primeiro` may be `[1,1]` while `Node` is `None`. I have tried to fix it but it always ends up not working later in the code...
I would be happy to get some help on this one! Using pandas 0.18.1 and your version 1.10.
Best

**Comment by csunlab** [comment]
Hello,
We can have a look at the problem. Would you be able to send us the file you are using as well? Or at least part of the file that reproduces the problem? We would be able to determine whether the problem comes from your file or the code? You can find our email address on the contact page of the CSUN website (csun.uic.edu).
Best,
CSUN

**Comment by csunlab** [comment]
Thanks for contacting us directly. We saw that the problem came with your shapefile. This issue is closed.
